import json

import pytest

from local_code_worker.exceptions import ResponseError
from local_code_worker.response_parser import parse_model_response


def test_parse_model_response_accepts_structured_json() -> None:
    payload = {
        "summary": "Changed service",
        "files": [{"path": "src/service.py", "content": "VALUE = 2\n", "reason": "Task"}],
    }
    response = parse_model_response(json.dumps(payload))
    assert response.files[0].content == "VALUE = 2\n"


def test_parse_model_response_extracts_one_fenced_json_object() -> None:
    payload = {
        "summary": "Changed service",
        "files": [
            {
                "path": "src/service.py",
                "content": 'VALUE = {"nested": true}\n',
                "reason": "Task",
            }
        ],
    }
    content = "I reviewed the task.\n\n```json\n" + json.dumps(payload) + "\n```"
    response = parse_model_response(content)
    assert response.files[0].content == 'VALUE = {"nested": true}\n'


def test_parse_model_response_adds_missing_summary_locally() -> None:
    payload = {
        "files": [{"path": "src/service.py", "content": "VALUE = 2\n", "reason": "Task"}],
    }
    response = parse_model_response(json.dumps(payload))
    assert response.summary == "Implementation generated by the model"


def test_parse_model_response_rejects_ambiguous_multiple_objects() -> None:
    payload = {
        "files": [{"path": "src/service.py", "content": "VALUE = 2\n", "reason": "Task"}],
    }
    content = json.dumps(payload) + "\n" + json.dumps(payload)
    with pytest.raises(ResponseError, match="Extra data"):
        parse_model_response(content)


def test_parse_model_response_rejects_invalid_json() -> None:
    with pytest.raises(ResponseError, match="Expecting value"):
        parse_model_response("not json")


def test_parse_model_response_rejects_empty_response() -> None:
    with pytest.raises(ResponseError, match="empty"):
        parse_model_response("  ")
