import json
from dataclasses import dataclass

from pydantic import ValidationError

from .exceptions import ResponseError
from .models import ModelImplementationResponse, ResponseStatus

REFUSAL_PHRASES = (
    "can't assist",
    "cannot assist",
    "can not assist",
    "unable to assist",
    "won't assist",
    "will not assist",
    "can't help",
    "cannot help",
    "unable to help",
    "not able to help",
    "must refuse",
    "i refuse",
    "i'm sorry",
    "i am sorry",
)


@dataclass(frozen=True)
class ParsedResponse:
    status: ResponseStatus
    response: ModelImplementationResponse | None
    error: str | None


def classify_model_response(content: str) -> ParsedResponse:
    if not content.strip():
        return ParsedResponse(
            ResponseStatus.EMPTY_RESPONSE, None, "Model returned an empty response"
        )
    try:
        payload = json.loads(content)
    except json.JSONDecodeError as error:
        payload = _extract_single_implementation_object(content)
        if payload is not None:
            return _validate_payload(payload, content)
        if _looks_like_refusal(content):
            return ParsedResponse(
                ResponseStatus.PROVIDER_REFUSAL, None, "Provider returned a refusal"
            )
        return ParsedResponse(ResponseStatus.INVALID_JSON, None, str(error))

    return _validate_payload(payload, content)


def _validate_payload(payload: object, content: str) -> ParsedResponse:
    payload = _add_safe_metadata_defaults(payload)
    if _looks_like_refusal(content) and not _has_implementation_shape(payload):
        return ParsedResponse(ResponseStatus.MODEL_REFUSAL, None, "Provider returned a refusal")
    try:
        response = ModelImplementationResponse.model_validate(payload)
    except ValidationError as error:
        return ParsedResponse(ResponseStatus.SCHEMA_VALIDATION_FAILED, None, str(error))
    return ParsedResponse(ResponseStatus.VALID, response, None)


def _extract_single_implementation_object(content: str) -> dict[str, object] | None:
    candidates: list[dict[str, object]] = []
    for candidate in _top_level_object_candidates(content):
        try:
            payload = json.loads(candidate)
        except json.JSONDecodeError:
            continue
        if isinstance(payload, dict) and isinstance(payload.get("files"), list):
            candidates.append(payload)
    return candidates[0] if len(candidates) == 1 else None


def _top_level_object_candidates(content: str) -> list[str]:
    candidates: list[str] = []
    start: int | None = None
    depth = 0
    in_string = False
    escaped = False
    for index, character in enumerate(content):
        if start is None:
            if character == "{":
                start = index
                depth = 1
            continue
        if in_string:
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == '"':
                in_string = False
            continue
        if character == '"':
            in_string = True
        elif character == "{":
            depth += 1
        elif character == "}":
            depth -= 1
            if depth == 0:
                candidates.append(content[start : index + 1])
                start = None
    return candidates


def _add_safe_metadata_defaults(payload: object) -> object:
    if (
        isinstance(payload, dict)
        and "summary" not in payload
        and isinstance(payload.get("files"), list)
        and payload["files"]
    ):
        return {**payload, "summary": "Implementation generated by the model"}
    return payload


def _looks_like_refusal(content: str) -> bool:
    normalized = " ".join(content.lower().replace("’", "'").split())
    return any(phrase in normalized for phrase in REFUSAL_PHRASES)


def _has_implementation_shape(payload: object) -> bool:
    return isinstance(payload, dict) and "summary" in payload and "files" in payload


def parse_model_response(content: str) -> ModelImplementationResponse:
    parsed = classify_model_response(content)
    if parsed.response is None:
        raise ResponseError(parsed.error or f"Model response status: {parsed.status}")
    return parsed.response
